/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:80e80e55-b550-41d5-858b-3ce1f2d65b6a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wdiyUB70Q",
    "aws_user_pools_web_client_id": "4phvemg6vaig03djm5l2me1k2g",
    "oauth": {}
};


export default awsmobile;
